sysctlTuner:
  params:
    # More options are in http://www.brendangregg.com/blog/2017-12-31/reinvent-netflix-ec2-tuning.html
    # You can add them into cm/addon-operator
    vm.swappiness: 0
    # # NUMA affinity should be tuned in another way
    kernel.numa_balancing: 0
    net.core.somaxconn: 1000
  sleep: 600
